-- Iscas: colunas extras + seed das 29 (rodar no SQL Editor)
alter table public.blog_templum_iscas add column if not exists slug text;
alter table public.blog_templum_iscas add column if not exists image_url text;
alter table public.blog_templum_iscas add column if not exists segment text;
create unique index if not exists blog_templum_iscas_slug_idx on public.blog_templum_iscas (slug);

insert into public.blog_templum_iscas (title, slug, type, description, file_url, segment, active) values
('Como Medir Processos na ISO 9001', 'como-medir-processos-na-iso-9001', 'ebook', 'Ebook gratuito Templum: como definir indicadores que importam na ISO 9001, do mapeamento à coleta, sem virar relatório morto.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1763406700336e-book.pdf', 'Qualidade e Inovação', true),
('Gestão de Processos, do Contexto ao Resultado', 'gestao-de-processos-do-contexto-ao-resultado-que-importa', 'ebook', 'Ebook Templum: como estruturar a gestão de processos partindo do contexto da organização e chegando em resultado mensurável.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1757682749264templum_sistemas_gestao.pdf', 'Qualidade e Inovação', true),
('ISO 27001, Guia de Mapeamento de Processos', 'iso-27001-o-guia-completo-para-mapeamento-de-processos', 'ebook', 'Como mapear processos para ISO 27001 (Segurança da Informação): escopo, ativos, controles e evidências, com método pronto para auditoria.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1757683310583mapeamento_processos_iso_templum.pdf', 'Segurança e Compliance', true),
('Lucre com a ISO 9001, Transição e Implantação', 'e-book-lucre-com-a-iso', 'ebook', 'Ebook Templum: como transformar a ISO 9001 em alavanca de resultado, não em custo de certificação. Caminho prático de implantação e transição.', 'https://certificacaoiso.com.br/wp-content/uploads/2021/07/ISO-9001-2015-COMO-FAZER-A-TRANSICAO.pdf', 'Qualidade e Inovação', true),
('Integração NRs com ISO 45001', 'integracao-nr-com-iso-45001-guia-completo-para-saude-e-seguranca', 'ebook', 'Ebook gratuito: como integrar Normas Regulamentadoras (NRs) com ISO 45001 sem duplicar esforço, método prático para SST.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1764634142176ebook_nrs_iso45001_20251201233801.pdf', 'Saúde e Segurança do Trabalho', true),
('ISO 45001, Perigos e Riscos', 'iso-45001-perigos-e-riscos-gestao-proativa-e-sustentavel', 'ebook', 'Como identificar perigos e avaliar riscos ocupacionais alinhado à ISO 45001, método prático, com matriz e plano de ação.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1758196838656iso_45001_perigos_riscos.pdf', 'Saúde e Segurança do Trabalho', true),
('A Nova ISO 45001, Mudanças e Implementação', 'e-book-a-nova-iso-45001', 'ebook', 'Guia completo sobre a ISO 45001: estrutura, cláusulas, integração com NRs e caminho de implementação.', 'https://certificacaoiso.com.br/wp-content/uploads/2021/07/ISO-45001.pdf', 'Saúde e Segurança do Trabalho', true),
('Análise Crítica pela Direção ISO 14001', 'analise-critica-pela-direcao-iso-14001-guia-completo-e-pratico', 'ebook', 'Guia prático de Análise Crítica pela Direção para ISO 14001, pauta, entradas, saídas e exemplos prontos para usar.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1764245037472e-book.pdf', 'Meio Ambiente', true),
('Guia Completo PBQP-H', 'e-book-guia-pbqp-h', 'ebook', 'Guia gratuito sobre o PBQP-H, níveis, exigências, certificação e como acessar o financiamento da Caixa.', 'https://certificacaoiso.com.br/sucesso-e-book-guia-pbqp-h/', 'Construção Civil', true),
('PBQP-H e Norma de Desempenho', 'e-book-pbqp-h-e-a-norma-de-desempenho', 'ebook', 'Como atender PBQP-H integrado à NBR 15575 (Norma de Desempenho), diferenças, sobreposições e plano único.', 'https://drive.google.com/file/d/1ftPOxZzKpnprB4xRTB42VCUPMvtNchzk/view?usp=sharing', 'Construção Civil', true),
('Mitos e Verdades do PBQP-H', 'e-book-mitos-e-verdades-do-pbqp-h', 'ebook', 'Os mitos mais comuns sobre PBQP-H desmontados, com as verdades práticas para quem vai certificar.', 'https://drive.google.com/file/d/1ftPOxZzKpnprB4xRTB42VCUPMvtNchzk/view?usp=sharing', 'Construção Civil', true),
('Gestão de Indicadores em Obras', 'gestao-de-indicadores-em-obras-eficiencia-e-resultados-reais', 'ebook', 'Indicadores que importam em obras, produtividade, perda, prazo, qualidade e segurança, com modelo de coleta e análise.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1763551656194e-book.pdf', 'Construção Civil', true),
('Regularização para Ramo Alimentício', 'e-book-regularizacao-para-ramo-alimenticio', 'ebook', 'Como regularizar uma empresa do setor alimentício, alvarás, ANVISA, MAPA e boas práticas que evitam interdição.', 'https://drive.google.com/file/d/1mBu0VaikWpCUQCnM60xjYOWIXYC5_oTc/view?usp=sharing', 'Segurança dos Alimentos', true),
('Segurança de Alimentos, Guia Prático', 'e-book-seguranca-de-alimentos', 'ebook', 'Como implementar segurança de alimentos com base em FSSC 22000, ISO 22000 e Codex Alimentarius, método prático.', 'https://drive.google.com/file/d/1mBu0VaikWpCUQCnM60xjYOWIXYC5_oTc/view?usp=sharing', 'Segurança dos Alimentos', true),
('Estudo de Caso FSSC 22000', 'e-book-estudo-de-caso-fssc-22000', 'ebook', 'Estudo de caso real de implementação FSSC 22000, etapas, desafios e resultados de uma indústria de alimentos.', 'https://drive.google.com/file/d/1mBu0VaikWpCUQCnM60xjYOWIXYC5_oTc/view?usp=sharing', 'Segurança dos Alimentos', true),
('OKR na Prática', 'e-book-okr', 'ebook', 'Como implementar OKR (Objectives and Key Results) na sua empresa, método, exemplos e armadilhas para evitar.', 'https://certificacaoiso.com.br/wp-content/uploads/2022/10/Ebook-OKR-Templum.pdf', 'Gestão e Marketing', true),
('Gestão de Relacionamentos, Setor Contábil', 'e-book-gestao-de-relacionamentos', 'ebook', 'Como estruturar gestão de relacionamento com cliente em escritórios contábeis para reduzir churn e aumentar LTV.', 'https://certificacaoiso.com.br/wp-content/uploads/2021/05/e-book-gestao-relacionamento-contabeis_v2-1.pdf', 'Gestão e Marketing', true),
('Ebook Templum para Empresários', 'ebook-empresarios', 'ebook', 'Material Templum para empresários: gestão, certificação e crescimento estruturado, visão estratégica para tomar decisão.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1743787584571Ebook%20Templum%20(1).pdf', 'Qualidade e Inovação', true),
('Inteligência Artificial na Prática', 'inteligencia-artificial-como-transformar-sua-empresa-com-ia-na-pratica', 'ebook', 'Como aplicar IA na gestão da sua empresa, casos práticos, ferramentas e roteiro para implementar sem desperdício.', 'https://d335luupugsy2.cloudfront.net/cms/files/965028/1763995382936e-book.pdf', 'IA', true),
('Planilha de Riscos e Oportunidades', 'planilha-riscos-e-oportunidades', 'planilha', 'Planilha gratuita para gestão de riscos e oportunidades alinhada à ISO 9001:2015, identificação, análise, tratamento e monitoramento.', 'https://docs.google.com/spreadsheets/d/1xjXkGR1YwMprobDCS9iimSUgKIQxUFNc9i54S6_v3QE/copy', 'Qualidade e Inovação', true),
('Planilha de Plano Operacional', 'planilha-plano-operacional', 'planilha', 'Planilha pronta para estruturar o plano operacional da sua empresa, metas, ações, responsáveis e prazos.', 'https://docs.google.com/spreadsheets/d/1xjXkGR1YwMprobDCS9iimSUgKIQxUFNc9i54S6_v3QE/copy', 'Qualidade e Inovação', true),
('Planilha de Controle de Mudança', 'planilha-controle-de-mudanca', 'planilha', 'Planilha pronta para gestão de mudanças em sistema de gestão (ISO 9001, 14001, 45001), registro, análise de impacto, aprovação e implementação.', 'https://docs.google.com/spreadsheets/d/1xjXkGR1YwMprobDCS9iimSUgKIQxUFNc9i54S6_v3QE/copy', 'Saúde e Segurança do Trabalho', true),
('Planilha de Relatório de Não Conformidade', 'planilha-relatorio-de-nao-conformidade', 'planilha', 'Planilha pronta para registro e tratamento de não conformidades, com causa raiz, ação corretiva e verificação de eficácia.', 'https://docs.google.com/spreadsheets/d/1xjXkGR1YwMprobDCS9iimSUgKIQxUFNc9i54S6_v3QE/copy', 'Qualidade e Inovação', true),
('Planilha de Mapeamento SGI', 'planilha-mapeamento-sgi', 'planilha', 'Planilha para mapear o Sistema de Gestão Integrado (ISO 9001 + 14001 + 45001), processos, riscos e indicadores em um só lugar.', 'https://certificacaoiso.com.br/wp-content/uploads/2021/04/Mapa-Processo-SGI.xlsx', 'Saúde e Segurança do Trabalho', true),
('Planilha PQO, Plano de Qualidade da Obra', 'planilha-pqo-plano-de-qualidade-da-obra', 'planilha', 'Planilha pronta de Plano de Qualidade da Obra (PQO) alinhada ao PBQP-H, controle de serviços, inspeções e materiais.', 'https://docs.google.com/spreadsheets/d/1xjXkGR1YwMprobDCS9iimSUgKIQxUFNc9i54S6_v3QE/copy', 'Construção Civil', true),
('Planilha de Perigos e Riscos', 'planilha-planilha-perigos-e-riscos', 'planilha', 'Planilha pronta para identificação de perigos e avaliação de riscos ocupacionais, aderente à NR-01 e ISO 45001.', 'https://certificacaoiso.com.br/wp-content/uploads/2021/04/Planilha-Perigos-e-Riscos-da-Templum-Consultoria.xlsx', 'Saúde e Segurança do Trabalho', true),
('Planilha de Controle de Estoque', 'planilha-controle-de-estoque', 'planilha', 'Planilha completa para controle de estoque, entrada, saída, mínimo, máximo e alerta de reposição.', 'https://certificacaoiso.com.br/wp-content/uploads/2021/04/Controle-de-Estoque.xlsx', 'Gestão e Marketing', true),
('Planilha Tartaruga Turbinada', 'planilha-tartaruga-turbinada', 'planilha', 'Diagrama Tartaruga em planilha, método clássico para mapear processo com entradas, saídas, recursos, controles e indicadores.', 'https://certificacaoiso.com.br/wp-content/uploads/2021/04/Tartatuga-Turbinada.xlsx', 'Qualidade e Inovação', true),
('Planilha de Fluxo de Caixa', 'planilha-fluxo-de-caixa', 'planilha', 'Planilha de fluxo de caixa simplificado, entradas, saídas, saldo projetado e gestão de contas a pagar e receber.', 'https://certificacaoiso.com.br/wp-content/uploads/2021/04/Modelo-de-Fluxo-de-Caixa-Simplificado-Templum-2.xlsx', 'Gestão e Marketing', true)
on conflict (slug) do update set title=excluded.title, type=excluded.type, description=excluded.description, file_url=excluded.file_url, segment=excluded.segment;
